### ISSUE TITLE
Demo import is not working

### ISSUE THREAD

**Issue by nodarik** [puikinsh/tyche#72] opened 2021-09-08 07:58 UTC
Demo import still has an issues, more in this ticket:
https://colorlibsupport.com/t/is-tyche-theme-discontinued/26765/4

**Comment by mahendrapratap4022** [comment] 2021-09-22 09:41
Hey, Please use this file for now. we will update it on the live server soon.
[tychedemo.wordpress.txt](https://github.com/ColorlibHQ/tyche/files/6999242/tychedemo.wordpress.txt)

Also, Please update txt with XML as the XML file is not supported here so I've changed the file extension.

[duplicate of [issue](https://github.com/ColorlibHQ/tyche/issues/71)]

**Closed as completed by mahendrapratap4022** 2021-09-22 09:41 UTC
