### ISSUE TITLE
missing the demo price slider widget from the shop

### ISSUE THREAD

**Issue by angelz12** [puikinsh/tyche#32] opened 2017-09-25 19:28 UTC
the point is that the correct slider on the demo not working 
https://cdn.colorlib.com/wp/wp-content/uploads/sites/2/2-23.jpg
watch my screenshot do you know why?

**Comment by cristeacosmin** [comment] 2017-10-09 10:31
Hello,

Can you provide more information on this issue? I-ve tested this with the latest version 1.0.12 and seems to be working fine ( version will be released later today, let me know if the issue persists )

Releases will be updated here: 
https://github.com/puikinsh/tyche/releases

**Comment by a-support** [comment] 2018-04-25 11:54
Hello,

I can confirm that the price filter works.

**Comment by cristianraiber** [comment] 2018-04-25 12:09
Closing since @a-support reported this is now working fine indeed.

**Closed as completed** 2018-04-25 12:09 UTC
Labels: tested
